---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitea
  namespace: default
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "15"
spec:
  interval: 10m0s
  url: https://dl.gitea.io/charts/
