---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tidb-operator
  namespace: default
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "15"
spec:
  interval: 5m
  chart:
    spec:
      chart: tidb-operator
      version: 'v1.3.2'
      sourceRef:
        kind: HelmRepository
        name: tidb-operator
        namespace: default
      interval: 1m
  values:
