k8s_yaml(helm('.', name='schemahero', namespace='schemahero-system', values=['./values.tilt.yaml']))

k8s_resource(
    workload='schemahero',
    objects=[
        'schemahero-system:namespace',
        'databases.databases.schemahero.io:customresourcedefinition',
        'tables.schemas.schemahero.io:customresourcedefinition',
        'migrations.schemas.schemahero.io:customresourcedefinition',
        'schemahero-role:clusterrole',
        'schemahero-rolebinding:clusterrolebinding',
        'webhook-server-secret:secret'
    ],
    labels=['schemahero']
)
