---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: medulla
    service: identity
data:
  ASPNETCORE_URLS: http://0.0.0.0:8080
  IssuerUrl: {{ .Values.hostName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: {{ .Release.Namespace }}
  labels:
    app: medulla
    service: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      service: identity
  template:
    metadata:
      labels:
        app: medulla
        service: identity
    spec:
      containers:
        - name: identity
          image: ghcr.io/recro/medulla/identity:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: identity-cm
---
apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: {{ .Release.Namespace }}
  labels:
    app: medulla
    service: identity
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: identity
