---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medulla
  namespace: {{ .Release.Namespace }}
  labels:
    app: medulla
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: {{ .Values.hostName }}
      http:
        paths:
          - path: /identity
            pathType: Prefix
            backend:
              service:
                name: identity
                port:
                  number: 8080
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: documentation
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shell
                port:
                  number: 8080
