---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shell-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: medulla
    service: shell
data:
  ASPNETCORE_URLS: http://0.0.0.0:8080
  IssuerUrl: https://{{ .Values.hostName }}/identity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: {{ .Release.Namespace }}
  labels:
    app: medulla
    service: shell
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shell
  template:
    metadata:
      labels:
        app: medulla
        service: shell
    spec:
      containers:
        - name: shell
          image: ghcr.io/recro/medulla/shell:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: shell-cm
---
apiVersion: v1
kind: Service
metadata:
  name: shell
  namespace: {{ .Release.Namespace }}
  labels:
    app: medulla
    service: shell
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: shell
