apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: application.medulla.io
spec:
  group: medulla.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: application
    singular: application
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: A CustomResourceDefinition which allows building with data in Medulla.
        properties:
          spec:
            description: Spec is is an element of the V1Alpha1ApplicationEntity  which is a list of type ApplicationSpec
            items:
              properties:
                name:
                  description: Name is is an element of the ApplicationSpec which is the name of the Application created by Medulla
                  type: string
                description:
                  description: Description is is an element of the ApplicationSpec which is the description of the Application created by Medulla
                  type: string
              required:
              - name
              - description
              type: object
            type: array
          organization:
            description: A CustomResourceDefinition which allows building with organization in Medulla.
            properties:
              spec:
                description: Spec is a list elements of type Organization
                items:
                  properties:
                    name:
                      description: Name is an element of ModelSpec which is the name of the model/table
                      type: string
                  required:
                  - name
                  type: object
                type: array
              metadata:
                description: The metadata of the kubernetes object.
                type: object
              apiVersion:
                type: string
              kind:
                type: string
            type: object
        required:
        - organization
        type: object
    served: true
    storage: true
