apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: application.medulla.recro.com
spec:
  group: medulla.recro.com
  names:
    kind: Application
    listKind: ApplicationList
    plural: application
    singular: application
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: A CustomResourceDefinition which allows building with data in Medulla.
        properties:
          spec:
            items:
              properties:
                name:
                  nullable: true
                  type: string
                description:
                  nullable: true
                  type: string
              required:
              - name
              - description
              type: object
            nullable: true
            type: array
        type: object
    served: true
    storage: true
