---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "15"
spec:
  interval: 5m
  chart:
    spec:
      chart: istiod
      version: '1.14.1'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
  dependsOn:
    - name: istio
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
