apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: pages.medulla.recro.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: medulla.recro.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                razor:
                  type: string
                cs:
                  type: string
                css:
                  type: string
                js:
                  type: string
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: pages
    # singular name to be used as an alias on the CLI and for display
    singular: page
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Page
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - pg