---
apiVersion: v1
kind: Service
metadata:
  name: documentation
  namespace: {{ .Release.Namespace }}
  labels:
    app: documentation
    service: documentation
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: documentation

