---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.shell.replicaCount }}
  selector:
    matchLabels:
      app: identity
      version: v1
  template:
    metadata:
      labels:
        app: identity
        version: v1
    spec:
      serviceAccountName: identity
      containers:
      - image: "{{ .Values.identity.image.repository }}:{{ .Values.identity.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: identity
        ports:
        - containerPort: 80
