---
apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: {{ .Release.Namespace }}
  labels:
    app: identity
    service: identity
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: identity
