---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: base
  namespace: istio-system
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: '1.14.0'
      sourceRef:
        kind: HelmRepository
        name: base
        namespace: istio-system
      interval: 1m
  values:
