apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service-deployment
  labels:
    app: database-service
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      serviceAccountName: database-service-account
      containers:
        - name: database-service
          image: keithlogan94/database-service:latest
          env:
            - name: LOAD_KUBERNETES_IN_CLUSTER
              value: "yes"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: {{ .Release.namespace }}
spec:
  type: NodePort
  selector:
    app: database-service
  ports:
    - protocol: TCP
      port: 5188
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: internal-database-service
  namespace: {{ .Release.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: database-service
  ports:
    - protocol: TCP
      port: 5188
      targetPort: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-service-cluster-role
rules:
  - apiGroups: [""]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["secrets","pods"]
    verbs: ["create", "get", "watch", "list"]
  - apiGroups: [ "medulla.recro.com" ]
    resources: [ "data" ]
    verbs: [ "create", "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: database-service-cluster-role-binding
  namespace: {{ .Release.namespace }}
subjects:
  - kind: ServiceAccount
    name: database-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: database-service-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-service-account
  namespace: {{ .Release.namespace }}
---


