apiVersion: apps/v1
kind: Deployment
metadata:
  name: actionclass
  labels:
    app: actionclass
    test: test
  annotations:
    fluxcd.io/tag.actionclass: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: actionclass
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: actionclass
    spec:
      containers:
      - name: actionclass
        image: codingkeith/actionclass
        imagePullPolicy: Always
        ports:
        - containerPort: 80

        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      tolerations:
      - key: "cattle.io/os"
        value: "linux"
        effect: "NoSchedule"      