---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "20"
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
