---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: default
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "20"
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-workflows
      version: '2.3.6'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 10m0s
  values:
