---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: '1.14.0'
      sourceRef:
        kind: HelmRepository
        name: gateway
        namespace: istio-ingress
      interval: 1m
  dependsOn:
    - name: istiod
      namespace: istio-system
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
