---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gateway
  namespace: istio-ingress
spec:
  interval: 10m0s
  url: https://istio-release.storage.googleapis.com/charts

