commonLabels:
  operator-element: operator-instance
resources:
- deployment.yaml
configMapGenerator:
- name: webhook-config
  literals:
  - KESTREL__ENDPOINTS__HTTP__URL=http://0.0.0.0:5000
  - DATABASE_SERVICE_HOST=34.72.107.28
  - DATABASE_SERVICE_PORT=5188
  - DATABASE_SERVICE_PROTOCOL=http
  - DATABASE_SYNC_SERVICE_PROTOCOL=http
  - DATABASE_SYNC_SERVICE_HOST=database-sync-service.default.svc.cluster.local
  - DATABASE_SYNC_SERVICE_PORT=3000
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
