k8s_yaml(helm('.', name='kubed', namespace='kube-system', values=['./values.tilt.yaml']))

k8s_resource(
    workload='kubed',
    objects=[
        'kubed:serviceaccount',
        'kubed:clusterrole',
        'kubed-apiserver-extension-server-authentication-reader:rolebinding',
        'kubed-apiserver-auth-delegator:clusterrolebinding',
        'kubed:clusterrolebinding',
        'kubed-apiserver-cert:secret',
        'kubed:secret'
    ],
    labels=['kubed']
)
