# Before running Tye make sure you have a local Kubernetes cluster running

name: Medulla
namespace: medulla-system
network: medulla

ingress:
  - name: medulla
    bindings:
      - name: http
        port: 8080
        protocol: http
      - name: https
        port: 443
        protocol: https
    rules:
      - service: shell
        path: /
      - service: documentation
        path: /docs
        preservePath: true
      - service: identity
        path: /identity
        preservePath: true
      - service: database-service
        path: /database-service
        preservePath: false
      - service: database-designer
        path: /designer
        preservePath: false

services:
  - name: shell
    project: Shell/Server/Medulla.Shell.Server.csproj
    replicas: 1
    bindings:
      - name: http
        protocol: http

  - name: documentation
    project: Documentation/Server/Medulla.Documentation.Server.csproj
    replicas: 1
    bindings:
      - name: http
        protocol: http

  - name: identity
    project: Identity/Server/Medulla.Identity.Server.csproj
    replicas: 1
    bindings:
      - name: http
        protocol: http
        
  - name: database-service
    project: Medulla/Kubernetes/Database/DatabaseService/DatabaseService.csproj
    replicas: 1
    bindings:
      - name: http
        protocol: http
        
  - name: database-sync
    dockerFile: Medulla/Kubernetes/Database/DatabaseSync/Dockerfile
    replicas: 1
    bindings:
      - name: http
        port: 8085    

  - name: database-designer
    dockerFile: Medulla/Kubernetes/Database/DatabaseDesigner/Dockerfile
    replicas: 1
    bindings:
      - name: http
        protocol: http

  
  # Before you can run Tye with this Controller process
  # You need to install the Kubectl config manifests for the Controller
  # kubectl apply -k .\src\Medulla\Kubernetes\Operator\config\install\
  - name: controller
    project: Medulla/Kubernetes/Operator/Operator.csproj
    replicas: 1
    bindings:
      - name: http
        protocol: http
    env:
      - name: DATABASE_SYNC_SERVICE_PROTOCOL
        value: http
      - name: DATABASE_SYNC_SERVICE_HOST
        value: localhost
      - name: DATABASE_SYNC_SERVICE_PORT
        value: 8085

  - name: mysql
    image: mysql:latest
    replicas: 1
    bindings:
      - name: mysql
        protocol: http
        port: 3306


  - name: adminer
    image: adminer:latest
    replicas: 1
    bindings:
      - port: 8081
