name: Lint Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run linters
        uses: AndrewBabbitt97/lint-action@v1.12.0
        with:
          continue_on_error: false
          dotnet_format: true
          dotnet_format_dir: src/
