name: Release Medulla

on:
  release:
    types: [prereleased,released]

jobs:
  release:
    name: Release App
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Set up tye
        run: dotnet tool install -g Microsoft.Tye --version "0.11.0-alpha.22111.1"

      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push containers
        run: |
          export PATH=$HOME/.dotnet/tools:$PATH
          tye push src/

      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toTag: ${{ github.event.release.tag_name }}
          commitMode: true
          configuration: .github/changelog.json

      - name: Update release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          allowUpdates: true
          prerelease: ${{ github.event.release.prerelease }}
          body: ${{ steps.changelog.outputs.changelog }}
