---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr
  namespace: default
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  interval: 5m
  chart:
    spec:
      chart: dapr
      version: '1.7.2'
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: default
      interval: 1m
  values: